name = "UNRMath466"
uuid = "0ac52957-8ab3-4f6d-9b73-0a1c5c80fa28"
authors = ["HamerZachary <66767197+HamerZachary@users.noreply.github.com>"]
version = "0.1.0"

[deps]
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
