function IncludedMethods()
    println("**Root Finding Methods")
    println("1. Bisection(a,b,f)")
    println("2. SingleRootSecant(x0,x1,f)")
    println("3. DoubleRootSecant(x0,x1,f)")
    println("4. Newton(x0,f,g)")
    println("")
    println("     a - Left interval endpoint")
    println("     b - Right interval endpoint")
    println("     x0 - Initial value")
    println("     x1 - Initial value + 1")
    println("     x - Initial point to start")
    println("     f - function")
    println("     g - derivative of function")
    println("")
    println("**Lagrangian Interpolation Methods")
    println("1. p(t,n)")
    println("2. PlotInterpolatedPolynomial(a,b)")
    println("")
    println("     a - Left interval endpoint of valid interpolation")
    println("     b - Right interval endpoint of valid interpolation")
end